# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adc61c7bc2e0475c3947553f69f293c8145cb296d1e28ba58205e49da074072c744c24ee6ee86694d2db597019656b9f83f9b07830751b8ad749d347d11b8729

test:
  secret_key_base: 2530ca69917d960e8ce4320ae9c98d76b2593c5f60ffca5fbe31981f6a7d80816c7a7fa5c83a60ac1b0e893e52c4df4615ebb36bb6298197867fc237d993ed57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
